#!/usr/bin/env bash

export CONTECO_LABEL="traefik.soleco - SolEco"
export CONTECO_DESCRIPTION="Simple Traefik solution, providing autodiscovery for solution services."

export CONTECO_TYPE="traefik"
export CONTECO_NAME="local"
export CONTECO_TAG="v1.0.0"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="soleco"
