- type: http
  id: external_traefik_gateway
  name: External Traefik Gateway
  hosts: ["http://:80"]
  check.response.status: [404]
  schedule: '@every 30s'
  fields:
    scope: "traefik_local"
    type: external
    service: traefik
    area: gateway
# source
- type: http
  id: internal_traefik_dashboard
  name: Internal Traefik Dashboard
  hosts: ["http://:8080/dashboard"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "traefik_local"
    type: internal
    service: traefik
    area: dashboard
