#!/usr/bin/env bash


	executionplane --silent docker volume create solution_traefik_local_metrics_monitor_heartbeat_data_volume
	
	executionplane --silent docker volume create solution_traefik_local_metrics_monitor_heartbeat_monitors_volume
	
executionplane --silent docker run -v solution_traefik_local_metrics_monitor_heartbeat_monitors_volume:/usr/share/heartbeat/monitors.d ${CONTECO_REGISTRY}$1 --interactive cp -r /soleco/_component/metrics_monitor_heartbeat_monitors_volume/* /usr/share/heartbeat/monitors.d
		
